# -*- coding: utf-8 -*-
"""01_Time_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ws3JNP7FDDxX68SSJ2--MM3M6bXA7OTN
"""

!git clone https://github.com/Vamsipradeep588/01_Time_Converter.git

!pip install pandas

import pandas as pd

"""
PlatinumRx Assignment | Phase 3 – Python
Script 1: Time Converter
========================
Given a number of minutes, convert it into a human-readable string.

Examples:
    130  →  "2 hrs 10 minutes"
    110  →  "1 hr 50 minutes"
    60   →  "1 hr 0 minutes"
    45   →  "0 hrs 45 minutes"
"""


def convert_minutes(total_minutes: int) -> str:
    """
    Convert an integer number of minutes into a human-readable string.

    Parameters
    ----------
    total_minutes : int
        Total duration in minutes (must be >= 0).

    Returns
    -------
    str
        Formatted string like "2 hrs 10 minutes".
    """
    if total_minutes < 0:
        return "Invalid input: minutes cannot be negative."

    hours           = total_minutes // 60       # integer division → whole hours
    remaining_mins  = total_minutes  % 60       # modulo → leftover minutes

    # Pluralisation for "hr" / "hrs"
    hr_label  = "hr"  if hours == 1 else "hrs"
    min_label = "minute" if remaining_mins == 1 else "minutes"

    return f"{hours} {hr_label} {remaining_mins} {min_label}"


# ── Main: test with sample inputs ───────────────────────────────────────────

if __name__ == "__main__":
    test_cases = [130, 110, 60, 45, 0, 1, 61, 999]

    print("=" * 40)
    print("  Time Converter – Results")
    print("=" * 40)
    for minutes in test_cases:
        result = convert_minutes(minutes)
        print(f"  {minutes:>5} minutes  →  {result}")
    print("=" * 40)

    # ── Interactive mode ─────────────────────────────────────
    print("\nEnter a number of minutes to convert (or 'q' to quit):")
    while True:
        user_input = input("  Minutes: ").strip()
        if user_input.lower() == 'q':
            print("Goodbye!")
            break
        try:
            mins = int(user_input)
            print(f"  Result : {convert_minutes(mins)}\n")
        except ValueError:
            print("  Please enter a valid integer.\n")

from google.colab import drive
drive.mount('/content/drive')