# -*- coding: utf-8 -*-
"""02_Remove_Duplicates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xiq7KhvCAWvl2K1YHc-PenRhnqTlcDJj
"""

!git clone https://github.com/Vamsipradeep588/02_Remove_Duplicates.git

!pip install pandas

import pandas as pd

"""
PlatinumRx Assignment | Phase 3 – Python
Script 2: Remove Duplicate Characters
======================================
Given a string, remove all duplicate characters using a loop
and print the resulting unique string (preserving first-occurrence order).

Examples:
    "programming"  →  "progamin"
    "hello world"  →  "helo wrd"
    "aabbcc"       →  "abc"
"""


def remove_duplicates(input_string: str) -> str:
    """
    Remove duplicate characters from a string using a loop.
    The first occurrence of every character is kept;
    subsequent duplicates are discarded.

    Parameters
    ----------
    input_string : str
        The raw string that may contain duplicate characters.

    Returns
    -------
    str
        A new string with each character appearing exactly once,
        in the order they first appeared.
    """
    result = ""                         # start with an empty string

    for char in input_string:          # loop through every character
        if char not in result:          # only add if not already seen
            result += char              # append first-occurrence characters

    return result


# ── Main: test with sample inputs ───────────────────────────────────────────

if __name__ == "__main__":
    test_cases = [
        "programming",
        "hello world",
        "aabbcc",
        "PlatinumRx",
        "data analyst",
        "mississippi",
        "",                             # edge case: empty string
        "a",                            # edge case: single character
        "aaaa",                         # edge case: all same characters
    ]

    print("=" * 50)
    print("  Remove Duplicates – Results")
    print("=" * 50)
    for s in test_cases:
        unique = remove_duplicates(s)
        print(f"  Input  : {repr(s)}")
        print(f"  Output : {repr(unique)}")
        print("-" * 50)

    # ── Interactive mode ─────────────────────────────────────
    print("\nEnter a string to remove duplicates (or 'q' to quit):")
    while True:
        user_input = input("  String : ")
        if user_input.lower() == 'q':
            print("Goodbye!")
            break
        print(f"  Result : {remove_duplicates(user_input)}\n")

from google.colab import drive
drive.mount('/content/drive')